"""amnezia_subscription

Revision ID: c1b39da17899
Revises: 922342f1dac9
Create Date: 2026-05-27 21:48:08.784835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b39da17899'
down_revision: Union[str, None] = '922342f1dac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('wg_public_key', sa.String(length=64), nullable=False))
    op.add_column('subscriptions', sa.Column('wg_config', sa.String(length=2048), nullable=False))
    op.drop_column('subscriptions', 'xui_client_uuid')
    op.drop_column('subscriptions', 'traffic_limit_gb')
    op.drop_column('subscriptions', 'sub_link')
    op.drop_column('subscriptions', 'xui_client_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('xui_client_email', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('sub_link', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('traffic_limit_gb', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('xui_client_uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'wg_config')
    op.drop_column('subscriptions', 'wg_public_key')
    # ### end Alembic commands ###
